apiVersion: v1
kind: Secret
metadata:
  namespace: three-tier
  name: postgres-sec
type: Opaque
data:
  username: ZGV2b3BzX3VzZXI= # devops_user (base64 encoded)
  password: ZGV2b3BzX3Bhc3N3b3Jk # devops_password (base64 encoded)

