apiVersion: v1
kind: Secret
metadata:
  namespace: three-tier
  name: postgres-sec
type: Opaque
data:
  password: ZGV2b3BzX3VzZXI= # Replace with actual base64-encoded password
  username: ZGV2b3BzX3Bhc3N3b3Jk # Replace with actual base64-encoded username
